# Generated by Django 4.0.6 on 2022-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='weburl',
            field=models.TextField(blank=True, verbose_name='Ссылка'),
        ),
    ]
